# server
server:
  port: 18000
  servlet:
    context-path: /
spring:
  application:
    name: spring-boot-kafka
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  profiles:
    active: dev